 <?php   
    $category=Mage::registry('current_category');
    if ($category!=null){
       if ($category->getLevel()==2 ){
            echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_custom_slidebar_4')->toHtml();      
       }
       else{
            echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_custom_slidebar_3')->toHtml();      
       }
        
    }
        
     
         
 ?>
