<div class="nv-container padd-top">
<p>{{block type="revslideshow/view"}}</p>
<div class="banner-home">
<p>[container]</p>
<p>[one_third]<img src="{{media url="wysiwyg/sm-homepagebanner-01.jpg"}}" alt="download invitation template" />[/one_third]</p>
<p>[one_third]<a class="inline" href="http://www.youtube.com/watch?v=GIAkk8EIhwk?rel=0&amp;wmode=transparent&amp;vq=hd1080"><img src="{{media url="wysiwyg/sm-homepagebanner-02.jpg"}}" alt="how does it work" /></a>[/one_third]</p>
<p>[one_third]<img src="{{media url="wysiwyg/sm-homepagebanner-03.jpg"}}" alt="invitation programs printing" />[/one_third]</p>
<p>[/container]</p>
</div>
</div>
<p style="text-align: center;"><strong>Download. Edit. Print.</strong> Do it yourself printable templates enable you to make professional invitations, announcements,<br /> programs or cards. All templates compatible with Microsoft Word&reg;, OpenOffice&reg;, Publisher&reg;, and Apple iWork Pages&reg;.</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">&nbsp;&nbsp;{{block type="ajaxhometabs/showTabs" name="showTabs" template="ajaxhometabs/showTabs.phtml"}}</p>
<p style="text-align: center;">&nbsp;</p>
<p><br />Our Other Brands:
    <a href="http://www.funeralprogram-site.com">
        <img style="margin-left: 10px; margin-right: 10px; vertical-align: middle;" src="{{media url="wysiwyg/logo-wide.jpg"}}" alt="funeral programs site" width="267" height="54" />
    </a>
    <a href="http://www.mediavoicepro.com">
        <img style="margin-left: 5px; margin-right: 5px; vertical-align: middle;" src="{{media url="wysiwyg/mediavoicepro-website.jpg"}}" alt="media voice pro templates" />
    </a>
    <a href="http://www.wisteriapress.com">
        <img style="vertical-align: middle;" src="{{media url="wysiwyg/wisteria-press.jpg"}}" alt="wisteria press" />
    </a>
</p>
<script type="text/javascript">
    	jQuery.noConflict();
		jQuery(document).ready(function(){	
			alert(1);
                       jQuery(".inline").colorbox({iframe:true, innerWidth:640, innerHeight:390});
                   
		});
</script>